### ISSUE TITLE
java.lang.UnsupportedOperationException when updating entity properties

### ISSUE THREAD

**Issue by Inventoroz** [odpi/egeria-connector-xtdb#278]
Here is the stack trace: [Egeria Error Stack Trace.txt](https://github.com/odpi/egeria-connector-xtdb/files/7675278/Egeria.Error.Stack.Trace.txt)

If need full stack trace: 
[Full Stack Trace.txt](https://github.com/odpi/egeria-connector-xtdb/files/7675380/Full.Stack.Trace.txt)

It seems likely that there is an attempt of using immutable structure from Clojure as mutable.
https://github.com/clojure/clojure/blob/abe19832c0294fec4c9c55430c9262c4b6d2f8b1/src/jvm/clojure/lang/APersistentVector.java#L247

**Comment by cmgrote** [comment]
😱 🙈 yikes -- schoolboy error on my part. Thank you for finding this!

I should have a fix in shortly, but just want to do a quick scan through the rest of the code to make sure I'm not making the same mistake elsewhere first...

**Comment by cmgrote** [comment]
Ok, this should be fixed in the latest snapshot now: https://oss.sonatype.org/content/repositories/snapshots/org/odpi/egeria/egeria-connector-xtdb/3.4-SNAPSHOT/egeria-connector-xtdb-3.4-20211208.123952-7-jar-with-dependencies.jar

Would you mind grabbing that (or rebuilding from the latest `main` branch of this connector repo), and re-testing?

I'll wait to ensure that this is resolved before creating the 3.4 release of the connector.

**Comment by Inventoroz** [comment]
Thanks It works

**Comment by cmgrote** [comment]
For completeness, the error was that the connector code was doing an unchecked casting of a return value from XT into a `List<String>` (a mutable Java structure) while in fact what was being returned from XT was an `IPersistentVector` (an immutable Clojure structure).

The error was related to updating the list of users that maintains a given metadata instance, which occurs on basically every update operation. This list of users is only changed if there are new users contributing to the changes -- if the same user repeatedly creates / modifies metadata instances, the list is unchanged, and thus this error is not observed.

Of course, it is perfectly logical that multiple users can contribute updates to a given piece of metadata, and Egeria is designed to allow this -- as is the connector. The problem was that because the connector was treating an immutable Clojure structure as a mutable Java structure, when the `.add()` method is called (against an `IPersistentVector`) this throws the `UnsupportedOperationException` (since the object is immutable, it cannot be `add`ed to).

The connector code has now been updated to:

- No longer incorrectly cast these return values, but instead to appropriately handle them as `IPersistentVector` structures (and only convert them to mutable Java structures when mutation is required)
- Add explicit unit tests for different users doing creations and updates of the same objects (ensuring the `.add()` method is always called at some point), which was initially used to reproduce the error and now will be used to ensure no regression is introduced
